"""Create tables

Revision ID: 2ad74e28e513
Revises: 
Create Date: 2024-12-14 17:12:15.513219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ad74e28e513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('is_superuser', 'not_superuser', name='superuser_status_enum').create(op.get_bind())
    sa.Enum('active', 'unactive', name='active_status_enum').create(op.get_bind())
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', postgresql.ENUM('active', 'unactive', name='active_status_enum', create_type=False), nullable=False),
    sa.Column('is_superuser', postgresql.ENUM('is_superuser', 'not_superuser', name='superuser_status_enum', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    sa.Enum('active', 'unactive', name='active_status_enum').drop(op.get_bind())
    sa.Enum('is_superuser', 'not_superuser', name='superuser_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
